solc successfully installed at: /root/.py-solc/solc-v0.4.25/bin/solc
==== Exception State ====
SWC ID: 110
Severity: Low
Contract: TelcoinSaleCapEscrow
Function name: fallback
PC address: 3780
Estimated Gas Usage: 1469 - 2084
A reachable exception has been detected.
It is possible to trigger an exception (opcode 0xfe). Exceptions can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. Note that explicit `assert()` should only be used to check invariants. Use `require()` for regular input checking.
--------------------
In file: /tmp/30101.sol:26

assert(c >= a)

--------------------
Transaction Sequence:

Caller: [CREATOR], data: [CONTRACT CREATION], value: 0x1
Caller: [SOMEGUY], function: unknown, txdata: 0x10042000, value: 0x1
Caller: [SOMEGUY], function: unknown, txdata: 0x08041002, value: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

